### ISSUE TITLE
Сhanging direction

### ISSUE THREAD

**Issue by Valavanca** [Valavanca/flexbox-slider#1]
Summa of translateX with +/- and changing order have resulted in 100%. This lead to jumping between elements

```css
#carousel.right {
  transform: translateX(33.33333%);
  transition: transform 2s cubic-bezier(0.23, 1, 0.32, 1);
}
#carousel.left {
  transform: translateX(-33.33333%);
  transition: transform 2s cubic-bezier(0.23, 1, 0.32, 1);
}
```
